# Generated by Django 3.2.8 on 2025-12-04 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('category', models.CharField(choices=[('gaming', 'Gaming'), ('music', 'Música'), ('talk', 'Charla / Talk'), ('education', 'Educación / Taller')], max_length=20, verbose_name='Categoría')),
                ('difficulty', models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='beginner', max_length=20, verbose_name='Nivel')),
                ('scheduled_for', models.DateTimeField(verbose_name='Fecha y hora programada')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programado'), ('live', 'En directo'), ('finished', 'Finalizado'), ('cancelled', 'Cancelado')], default='draft', max_length=20, verbose_name='Estado')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='events/thumbnails/', verbose_name='Imagen de portada')),
                ('max_viewers', models.PositiveIntegerField(default=100, verbose_name='Máximo de espectadores')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración prevista (minutos)')),
                ('tags', models.CharField(blank=True, help_text='Ejemplo: python, django, streaming', max_length=500, verbose_name='Etiquetas (separadas por comas)')),
                ('stream_url', models.URLField(blank=True, max_length=500, verbose_name='URL del streaming / demo')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Evento destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Creador')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['-scheduled_for', '-created_at'],
            },
        ),
    ]
